
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: installment_development
  username: installment
  password: rdenadark

test:
  <<: *default
  database: installment_test
  username: installment
  password: rdenadark

production:
  <<: *default
  database: installment_production
  username: installment
  password: rdenadark
